# From
# https://github.com/chanzuckerberg/napari-hub/blob/main/backend/category/data/EDAM-BIOIMAGING/hub-mapping-alpha06.json
labels:
  ontology: EDAM-BIOIMAGING:alpha06
  terms:
    - 3D image
    - Image time series
    - Image segmentation
    - Object tracking